# Site settings
title: Bit Podcast
email: benjaminreid.nouveller@gmail.com
description: "Bit Podcast is an ongoing series about games, design & development from the mouths of @DavidDarnes and @BenjaminReid"
baseurl: ""
url: "https://bitpodcast.com"
paginate: 5
paginate_path: "posts/:num"
logo: "https://pbs.twimg.com/profile_images/378800000000857377/558e6da9b796157ee71eb5ba111dfe56_400x400.png"

twitter:
  username: BitPodcast

author:
  twitter: BitPodcast

# Build settings
markdown: kramdown
permalink: pretty

# Podcast settings
lang: en
author: David Darnes and Benjamin Reid

# Jekyll plugins
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-paginate

jekyll-mentions: https://twitter.com
