# Site settings
title: Bit Podcast
email: benjaminreid.nouveller@gmail.com
description: "A few people talking about things"
baseurl: ""
url: "http://bitpodcast.com"

# Build settings
markdown: kramdown
permalink: pretty
